"""Provider transcript parsing for cross-session continuity."""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Callable, Iterable

from core.textutil import extract_text


MAX_TAIL_BYTES = 16 * 1024 * 1024
MAX_LINE_BYTES = 2 * 1024 * 1024
MAX_TURNS_PER_SESSION = 80
MAX_TURN_CHARS = 500

_SECRET_RE = re.compile(
    r"(-----BEGIN(?: [A-Z0-9]+)? PRIVATE KEY-----.*?"
    r"-----END(?: [A-Z0-9]+)? PRIVATE KEY-----"
    r"|(?:Cookie|Set-Cookie|Authorization|Proxy-Authorization)\s*:\s*[^\r\n]+"
    r"|[A-Za-z][A-Za-z0-9+.-]*://[^\s/@:]+:[^\s/@]+@"
    r"|(?<![A-Za-z0-9])(?:sk|rk)_(?:live|test)_[A-Za-z0-9_\-]{8,}"
    r"|(?<![A-Za-z0-9])sk-[A-Za-z0-9_\-]{8,}"
    r"|(?:gh[pousr]|github_pat)_[A-Za-z0-9_\-]{12,}"
    r"|(?:AKIA|ASIA)[A-Z0-9]{16}"
    r"|AIza[A-Za-z0-9_\-]{30,}"
    r"|xox[a-z]-[A-Za-z0-9-]{10,}"
    r"|Bearer\s+\S+"
    r"|eyJ[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}"
    r"|(?<![A-Za-z0-9_])[\"']?[A-Za-z0-9_\-]*"
    r"(?:token|secret|password|passwd|credential|cookie|session(?:[_ -]?id)?"
    r"|api[_ -]?key|access[_ -]?key|private[_ -]?key)"
    r"[A-Za-z0-9_\-]*[\"']?"
    r"\s*(?:is|[=:])\s*(?:[\"'][^\"']+[\"']|\S+))",
    re.IGNORECASE | re.DOTALL,
)
_SYNTHETIC_PREFIXES = (
    "This session is being continued from a previous conversation",
    "Caveat: The messages below were generated by the user while running local commands",
    "Set model to ",
    "你是一个对话压缩器",
    "The following is the Codex agent history whose request action",
    "Provider health canary.",
    "You are the Codex execution provider inside Jarvis.",
    "<system-reminder>",
    "<local-command-caveat>",
    "<command-name>",
    "<local-command-stdout>",
    "<task-notification>",
    "<teammate-message",
    "<user_action>",
    "<heartbeat>",
    "<automation",
)
_AUTOMATED_SESSION_PREFIXES = (
    "self improve ",
    "self-improve ",
    "[background task]",
    "[cross-session digest]",
    "review the code changes",
    "review the current code changes",
    "reply exactly codex_canary_ok",
)


@dataclass(frozen=True)
class Turn:
    role: str
    text: str
    timestamp: str = ""
    identity: str = ""


@dataclass(frozen=True)
class SessionTail:
    provider: str
    session_id: str
    workspace: str
    path: Path
    updated_at: str
    turns: tuple[Turn, ...]


def redact_text(value: object, limit: int = MAX_TURN_CHARS) -> str:
    """Collapse and redact transcript text before it enters any projection."""
    text = _SECRET_RE.sub("[redacted]", str(value or ""))
    text = re.sub(r"\s+", " ", text).strip()
    if len(text) > limit:
        text = text[:limit].rstrip() + "..."
    return text


def _is_synthetic(text: str) -> bool:
    clean = str(text or "").strip()
    return not clean or clean.startswith(_SYNTHETIC_PREFIXES)


def _turn_identity(provider: str, role: str, timestamp: str, raw_text: str) -> str:
    material = "\0".join((provider, role, timestamp, raw_text))
    return hashlib.sha256(material.encode("utf-8", errors="ignore")).hexdigest()


def _mtime_iso(path: Path) -> str:
    try:
        return datetime.fromtimestamp(path.stat().st_mtime).astimezone().isoformat(
            timespec="seconds")
    except OSError:
        return ""


def _tail_records(path: Path, max_bytes: int = MAX_TAIL_BYTES) -> list[dict]:
    """Read only a bounded JSONL tail and skip oversized tool-output records."""
    records: list[dict] = []
    try:
        with path.open("rb") as handle:
            size = handle.seek(0, 2)
            start = max(0, size - max(1, int(max_bytes)))
            handle.seek(start)
            if start:
                handle.readline()
            for raw in handle:
                if not raw or len(raw) > MAX_LINE_BYTES:
                    continue
                try:
                    item = json.loads(raw.decode("utf-8", errors="ignore"))
                except (json.JSONDecodeError, UnicodeDecodeError, ValueError):
                    continue
                if isinstance(item, dict):
                    records.append(item)
    except OSError:
        return []
    return records


def _head_records(path: Path, limit: int = 240) -> Iterable[dict]:
    try:
        with path.open("rb") as handle:
            for index, raw in enumerate(handle):
                if index >= limit:
                    break
                if not raw or len(raw) > MAX_LINE_BYTES:
                    continue
                try:
                    item = json.loads(raw.decode("utf-8", errors="ignore"))
                except (json.JSONDecodeError, UnicodeDecodeError, ValueError):
                    continue
                if isinstance(item, dict):
                    yield item
    except OSError:
        return


def _dedupe_adjacent(turns: Iterable[Turn]) -> tuple[Turn, ...]:
    result: list[Turn] = []
    for turn in turns:
        if result and result[-1].role == turn.role and result[-1].text == turn.text:
            continue
        result.append(turn)
    return tuple(result[-MAX_TURNS_PER_SESSION:])


def _recent_with_user(turns: Iterable[Turn], limit: int) -> tuple[Turn, ...]:
    """Keep the latest user objective even after many assistant updates."""
    items = tuple(turns)
    size = max(1, int(limit))
    selected = items[-size:]
    if any(turn.role == "user" for turn in selected):
        return selected
    latest_user = next(
        (turn for turn in reversed(items[:-size]) if turn.role == "user"),
        None,
    )
    if latest_user is None or size == 1:
        return (latest_user,) if latest_user is not None else selected
    return (latest_user, *selected[-(size - 1):])


def _claude_tail(
    path: Path,
    *,
    head_records: Callable[[Path], Iterable[dict]] = _head_records,
    tail_records: Callable[[Path], list[dict]] = _tail_records,
) -> SessionTail | None:
    for item in head_records(path):
        if item.get("isSidechain") or item.get("type") != "user":
            continue
        first_user = extract_text((item.get("message") or {}).get("content"))
        if _is_synthetic(first_user):
            continue
        if first_user.strip().lower().startswith(_AUTOMATED_SESSION_PREFIXES):
            return None
        break
    turns: list[Turn] = []
    session_id = path.stem
    workspace = ""
    for item in tail_records(path):
        if item.get("isSidechain") or item.get("type") not in {"user", "assistant"}:
            continue
        role = str(item.get("type") or "")
        raw_text = extract_text((item.get("message") or {}).get("content"))
        if _is_synthetic(raw_text):
            continue
        timestamp = str(item.get("timestamp") or "")
        text = redact_text(raw_text)
        if not text:
            continue
        session_id = str(item.get("sessionId") or session_id)
        workspace = str(item.get("cwd") or workspace)
        turns.append(Turn(
            role=role,
            text=text,
            timestamp=timestamp,
            identity=_turn_identity("claude", role, timestamp, raw_text),
        ))
    clean_turns = _dedupe_adjacent(turns)
    if not clean_turns:
        return None
    return SessionTail(
        provider="claude",
        session_id=session_id,
        workspace=workspace or path.parent.name,
        path=path,
        updated_at=_mtime_iso(path),
        turns=clean_turns,
    )


def _codex_meta(path: Path) -> dict:
    try:
        with path.open("rb") as handle:
            raw = handle.readline(MAX_LINE_BYTES)
        item = json.loads(raw.decode("utf-8", errors="ignore"))
    except (OSError, json.JSONDecodeError, UnicodeDecodeError, ValueError):
        return {}
    if item.get("type") != "session_meta":
        return {}
    payload = item.get("payload") or {}
    return payload if isinstance(payload, dict) else {}


def _codex_is_interactive(meta: dict) -> bool:
    source = meta.get("source")
    if meta.get("thread_source") == "subagent":
        return False
    if isinstance(source, dict) and "subagent" in source:
        return False
    source_name = str(source or "").lower()
    if source_name != "exec":
        return True
    return (
        str(meta.get("originator") or "").lower() == "codex desktop"
        and str(meta.get("thread_source") or "").lower() == "user"
    )


def _codex_initial_user(
    path: Path,
    *,
    head_records: Callable[[Path], Iterable[dict]] = _head_records,
) -> str:
    """Read the real first user request independently of the bounded tail."""
    for item in head_records(path):
        if item.get("type") != "event_msg":
            continue
        payload = item.get("payload") or {}
        if not isinstance(payload, dict) or payload.get("type") != "user_message":
            continue
        raw_text = str(payload.get("message") or "").strip()
        if _is_synthetic(raw_text):
            continue
        return raw_text
    return ""


def _codex_tail(
    path: Path,
    *,
    head_records: Callable[[Path], Iterable[dict]] = _head_records,
    tail_records: Callable[[Path], list[dict]] = _tail_records,
) -> SessionTail | None:
    meta = _codex_meta(path)
    if not _codex_is_interactive(meta):
        return None
    initial_user = _codex_initial_user(path, head_records=head_records)
    if initial_user.lower().startswith(_AUTOMATED_SESSION_PREFIXES):
        return None
    if str(meta.get("source") or "").lower() == "exec" and not initial_user:
        return None
    session_id = str(meta.get("id") or meta.get("session_id") or path.stem)
    workspace = str(meta.get("cwd") or "")
    turns: list[Turn] = []
    for item in tail_records(path):
        if item.get("type") != "event_msg":
            continue
        payload = item.get("payload") or {}
        if not isinstance(payload, dict):
            continue
        payload_type = payload.get("type")
        if payload_type == "user_message":
            role = "user"
        elif payload_type == "agent_message":
            role = "assistant"
        else:
            continue
        raw_text = str(payload.get("message") or "").strip()
        if _is_synthetic(raw_text):
            continue
        timestamp = str(item.get("timestamp") or payload.get("timestamp") or "")
        text = redact_text(raw_text)
        if not text:
            continue
        turns.append(Turn(
            role=role,
            text=text,
            timestamp=timestamp,
            identity=_turn_identity("codex", role, timestamp, raw_text),
        ))
    clean_turns = _dedupe_adjacent(turns)
    if not clean_turns or not any(turn.role == "user" for turn in clean_turns):
        return None
    return SessionTail(
        provider="codex",
        session_id=session_id,
        workspace=workspace or path.parent.name,
        path=path,
        updated_at=_mtime_iso(path),
        turns=clean_turns,
    )
