"""Owner-only continuity across interactive Claude Code and Codex sessions.

Provider-native transcripts stay authoritative and local.  This module reads a
small, redacted tail from owner-driven sessions for two bounded projections:

* ``incremental`` feeds the existing heartbeat digest with only unseen turns;
* ``context`` gives the main Lark agent immediate situational awareness, even
  before the next digest cycle succeeds.

Jarvis-managed sessions, headless Codex executions, health canaries, subagents,
reasoning, and tool payloads are excluded to prevent self-echo and private
implementation data from becoming conversation memory.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import time
import uuid
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Iterable

from core.textutil import extract_text


DEFAULT_WINDOW_HOURS = 24
SESSION_NAMESPACE = uuid.UUID("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
DEFAULT_STATE_FILE = "system/cross_session_seen.json"
MAX_SCAN_FILES = 240
MAX_TAIL_BYTES = 16 * 1024 * 1024
MAX_LINE_BYTES = 2 * 1024 * 1024
MAX_TURNS_PER_SESSION = 80
MAX_NEW_TURNS_PER_SESSION = 20
CONTEXT_TAIL = 3
MAX_INCREMENTAL_CHARS = 8000
MAX_CONTEXT_CHARS = 8000
MAX_CONTEXT_SESSIONS = 6
MAX_CONTEXT_TURNS = 6
MAX_TURN_CHARS = 500

_SECRET_RE = re.compile(
    r"(-----BEGIN(?: [A-Z0-9]+)? PRIVATE KEY-----.*?"
    r"-----END(?: [A-Z0-9]+)? PRIVATE KEY-----"
    r"|(?:Cookie|Set-Cookie|Authorization|Proxy-Authorization)\s*:\s*[^\r\n]+"
    r"|[A-Za-z][A-Za-z0-9+.-]*://[^\s/@:]+:[^\s/@]+@"
    r"|(?<![A-Za-z0-9])(?:sk|rk)_(?:live|test)_[A-Za-z0-9_\-]{8,}"
    r"|(?<![A-Za-z0-9])sk-[A-Za-z0-9_\-]{8,}"
    r"|(?:gh[pousr]|github_pat)_[A-Za-z0-9_\-]{12,}"
    r"|(?:AKIA|ASIA)[A-Z0-9]{16}"
    r"|AIza[A-Za-z0-9_\-]{30,}"
    r"|xox[a-z]-[A-Za-z0-9-]{10,}"
    r"|Bearer\s+\S+"
    r"|eyJ[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}"
    r"|(?<![A-Za-z0-9_])[\"']?[A-Za-z0-9_\-]*"
    r"(?:token|secret|password|passwd|credential|cookie|session(?:[_ -]?id)?"
    r"|api[_ -]?key|access[_ -]?key|private[_ -]?key)"
    r"[A-Za-z0-9_\-]*[\"']?"
    r"\s*(?:is|[=:])\s*(?:[\"'][^\"']+[\"']|\S+))",
    re.IGNORECASE | re.DOTALL,
)
_SYNTHETIC_PREFIXES = (
    "This session is being continued from a previous conversation",
    "Caveat: The messages below were generated by the user while running local commands",
    "Set model to ",
    "你是一个对话压缩器",
    "The following is the Codex agent history whose request action",
    "Provider health canary.",
    "You are the Codex execution provider inside Jarvis.",
    "<system-reminder>",
    "<local-command-caveat>",
    "<command-name>",
    "<local-command-stdout>",
    "<task-notification>",
    "<teammate-message",
    "<user_action>",
    "<heartbeat>",
    "<automation",
)
_AUTOMATED_SESSION_PREFIXES = (
    "self improve ",
    "self-improve ",
    "[background task]",
    "[cross-session digest]",
    "review the code changes",
    "review the current code changes",
    "reply exactly codex_canary_ok",
)


@dataclass(frozen=True)
class Turn:
    role: str
    text: str
    timestamp: str = ""
    identity: str = ""


@dataclass(frozen=True)
class SessionTail:
    provider: str
    session_id: str
    workspace: str
    path: Path
    updated_at: str
    turns: tuple[Turn, ...]


def redact_text(value: object, limit: int = MAX_TURN_CHARS) -> str:
    """Collapse and redact transcript text before it enters any projection."""
    text = _SECRET_RE.sub("[redacted]", str(value or ""))
    text = re.sub(r"\s+", " ", text).strip()
    if len(text) > limit:
        text = text[:limit].rstrip() + "..."
    return text


def _is_synthetic(text: str) -> bool:
    clean = str(text or "").strip()
    return not clean or clean.startswith(_SYNTHETIC_PREFIXES)


def _turn_identity(provider: str, role: str, timestamp: str, raw_text: str) -> str:
    material = "\0".join((provider, role, timestamp, raw_text))
    return hashlib.sha256(material.encode("utf-8", errors="ignore")).hexdigest()


def _mtime_iso(path: Path) -> str:
    try:
        return datetime.fromtimestamp(path.stat().st_mtime).astimezone().isoformat(
            timespec="seconds")
    except OSError:
        return ""


def _tail_records(path: Path, max_bytes: int = MAX_TAIL_BYTES) -> list[dict]:
    """Read only a bounded JSONL tail and skip oversized tool-output records."""
    records: list[dict] = []
    try:
        with path.open("rb") as handle:
            size = handle.seek(0, 2)
            start = max(0, size - max(1, int(max_bytes)))
            handle.seek(start)
            if start:
                handle.readline()
            for raw in handle:
                if not raw or len(raw) > MAX_LINE_BYTES:
                    continue
                try:
                    item = json.loads(raw.decode("utf-8", errors="ignore"))
                except (json.JSONDecodeError, UnicodeDecodeError, ValueError):
                    continue
                if isinstance(item, dict):
                    records.append(item)
    except OSError:
        return []
    return records


def _head_records(path: Path, limit: int = 240) -> Iterable[dict]:
    try:
        with path.open("rb") as handle:
            for index, raw in enumerate(handle):
                if index >= limit:
                    break
                if not raw or len(raw) > MAX_LINE_BYTES:
                    continue
                try:
                    item = json.loads(raw.decode("utf-8", errors="ignore"))
                except (json.JSONDecodeError, UnicodeDecodeError, ValueError):
                    continue
                if isinstance(item, dict):
                    yield item
    except OSError:
        return


def _dedupe_adjacent(turns: Iterable[Turn]) -> tuple[Turn, ...]:
    result: list[Turn] = []
    for turn in turns:
        if result and result[-1].role == turn.role and result[-1].text == turn.text:
            continue
        result.append(turn)
    return tuple(result[-MAX_TURNS_PER_SESSION:])


def _recent_with_user(turns: Iterable[Turn], limit: int) -> tuple[Turn, ...]:
    """Keep the latest user objective even after many assistant updates."""
    items = tuple(turns)
    size = max(1, int(limit))
    selected = items[-size:]
    if any(turn.role == "user" for turn in selected):
        return selected
    latest_user = next(
        (turn for turn in reversed(items[:-size]) if turn.role == "user"),
        None,
    )
    if latest_user is None or size == 1:
        return (latest_user,) if latest_user is not None else selected
    return (latest_user, *selected[-(size - 1):])


def _claude_tail(path: Path) -> SessionTail | None:
    for item in _head_records(path):
        if item.get("isSidechain") or item.get("type") != "user":
            continue
        first_user = extract_text((item.get("message") or {}).get("content"))
        if _is_synthetic(first_user):
            continue
        if first_user.strip().lower().startswith(_AUTOMATED_SESSION_PREFIXES):
            return None
        break
    turns: list[Turn] = []
    session_id = path.stem
    workspace = ""
    for item in _tail_records(path):
        if item.get("isSidechain") or item.get("type") not in {"user", "assistant"}:
            continue
        role = str(item.get("type") or "")
        raw_text = extract_text((item.get("message") or {}).get("content"))
        if _is_synthetic(raw_text):
            continue
        timestamp = str(item.get("timestamp") or "")
        text = redact_text(raw_text)
        if not text:
            continue
        session_id = str(item.get("sessionId") or session_id)
        workspace = str(item.get("cwd") or workspace)
        turns.append(Turn(
            role=role,
            text=text,
            timestamp=timestamp,
            identity=_turn_identity("claude", role, timestamp, raw_text),
        ))
    clean_turns = _dedupe_adjacent(turns)
    if not clean_turns:
        return None
    return SessionTail(
        provider="claude",
        session_id=session_id,
        workspace=workspace or path.parent.name,
        path=path,
        updated_at=_mtime_iso(path),
        turns=clean_turns,
    )


def _codex_meta(path: Path) -> dict:
    try:
        with path.open("rb") as handle:
            raw = handle.readline(MAX_LINE_BYTES)
        item = json.loads(raw.decode("utf-8", errors="ignore"))
    except (OSError, json.JSONDecodeError, UnicodeDecodeError, ValueError):
        return {}
    if item.get("type") != "session_meta":
        return {}
    payload = item.get("payload") or {}
    return payload if isinstance(payload, dict) else {}


def _codex_is_interactive(meta: dict) -> bool:
    source = meta.get("source")
    if meta.get("thread_source") == "subagent":
        return False
    if isinstance(source, dict) and "subagent" in source:
        return False
    source_name = str(source or "").lower()
    if source_name != "exec":
        return True
    # Recent Codex Desktop versions can represent an owner-visible task as
    # `exec`; retain those candidates, then reject known automation by their
    # first user turn in _codex_tail. Headless CLI/Jarvis executions stay out.
    return (
        str(meta.get("originator") or "").lower() == "codex desktop"
        and str(meta.get("thread_source") or "").lower() == "user"
    )


def _codex_initial_user(path: Path) -> str:
    """Read the real first user request independently of the bounded tail."""
    for item in _head_records(path):
        if item.get("type") != "event_msg":
            continue
        payload = item.get("payload") or {}
        if not isinstance(payload, dict) or payload.get("type") != "user_message":
            continue
        raw_text = str(payload.get("message") or "").strip()
        if _is_synthetic(raw_text):
            continue
        return raw_text
    return ""


def _codex_tail(path: Path) -> SessionTail | None:
    meta = _codex_meta(path)
    if not _codex_is_interactive(meta):
        return None
    initial_user = _codex_initial_user(path)
    if initial_user.lower().startswith(_AUTOMATED_SESSION_PREFIXES):
        return None
    if str(meta.get("source") or "").lower() == "exec" and not initial_user:
        # Desktop exec transcripts are admitted only with positive evidence of
        # an owner request. A drifted/oversized head must fail closed.
        return None
    session_id = str(meta.get("id") or meta.get("session_id") or path.stem)
    workspace = str(meta.get("cwd") or "")
    turns: list[Turn] = []
    for item in _tail_records(path):
        if item.get("type") != "event_msg":
            continue
        payload = item.get("payload") or {}
        if not isinstance(payload, dict):
            continue
        payload_type = payload.get("type")
        if payload_type == "user_message":
            role = "user"
        elif payload_type == "agent_message":
            role = "assistant"
        else:
            continue
        raw_text = str(payload.get("message") or "").strip()
        if _is_synthetic(raw_text):
            continue
        timestamp = str(item.get("timestamp") or payload.get("timestamp") or "")
        text = redact_text(raw_text)
        if not text:
            continue
        turns.append(Turn(
            role=role,
            text=text,
            timestamp=timestamp,
            identity=_turn_identity("codex", role, timestamp, raw_text),
        ))
    clean_turns = _dedupe_adjacent(turns)
    if not clean_turns or not any(turn.role == "user" for turn in clean_turns):
        return None
    return SessionTail(
        provider="codex",
        session_id=session_id,
        workspace=workspace or path.parent.name,
        path=path,
        updated_at=_mtime_iso(path),
        turns=clean_turns,
    )


def _read_mapping(path: Path | None) -> dict:
    if not path or not path.is_file():
        return {}
    try:
        loaded = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError, ValueError):
        return {}
    return loaded if isinstance(loaded, dict) else {}


def _managed_claude_ids(
    tracker_path: Path | None,
    jobs_registry_path: Path | None,
) -> set[str]:
    """Find Lark conversations and background Claude sessions owned by Jarvis."""
    tracker = _read_mapping(tracker_path)
    jobs = _read_mapping(jobs_registry_path)
    if not tracker and not jobs:
        return set()
    managed: set[str] = set()
    for conv_key, entry in tracker.items():
        if not isinstance(entry, dict):
            continue
        try:
            counter = max(0, int(entry.get("counter") or 0))
        except (TypeError, ValueError):
            counter = 0
        managed.update(
            str(uuid.uuid5(SESSION_NAMESPACE, f"{conv_key}-{index}"))
            for index in range(1, counter + 1)
        )
        if entry.get("session_id"):
            managed.add(str(entry["session_id"]))
    for entry in jobs.values():
        if not isinstance(entry, dict):
            continue
        if entry.get("session_id"):
            managed.add(str(entry["session_id"]))
        session_ids = entry.get("session_ids")
        if isinstance(session_ids, list):
            managed.update(str(value) for value in session_ids if value)
    return managed


def _paths(root: Path, provider: str) -> Iterable[Path]:
    if not root.is_dir():
        return ()
    if provider == "claude":
        # Top-level provider sessions only; nested files are Claude subagents.
        return root.glob("*/*.jsonl")
    return root.rglob("*.jsonl")


def discover_interactive_sessions(
    *,
    claude_root: str | Path | None = None,
    codex_root: str | Path | None = None,
    tracker_path: str | Path | None = None,
    jobs_registry_path: str | Path | None = None,
    window_hours: int = DEFAULT_WINDOW_HOURS,
    limit: int = MAX_CONTEXT_SESSIONS,
) -> list[SessionTail]:
    """Discover recent human-driven provider sessions, newest first."""
    home = Path.home()
    claude_root = Path(claude_root or os.environ.get("CROSS_SESSION_CLAUDE_ROOT")
                       or home / ".claude" / "projects")
    codex_root = Path(codex_root or os.environ.get("CROSS_SESSION_CODEX_ROOT")
                      or home / ".codex" / "sessions")
    if tracker_path is None:
        jarvis_dir = os.environ.get("JARVIS_DIR", "")
        tracker_path = Path(jarvis_dir) / "active_sessions.json" if jarvis_dir else None
    else:
        tracker_path = Path(tracker_path)
    if jobs_registry_path is None:
        jarvis_dir = os.environ.get("JARVIS_DIR", "")
        if jarvis_dir:
            jobs_registry_path = Path(jarvis_dir) / "jobs" / "registry.json"
        elif tracker_path and tracker_path.name == "active_sessions.json":
            jobs_registry_path = tracker_path.parent / "jobs" / "registry.json"
    else:
        jobs_registry_path = Path(jobs_registry_path)
    managed_claude = _managed_claude_ids(tracker_path, jobs_registry_path)
    cutoff = time.time() - max(1, int(window_hours)) * 3600
    candidates: list[tuple[float, str, Path]] = []
    for provider, root in (("claude", claude_root), ("codex", codex_root)):
        for path in _paths(root, provider):
            try:
                mtime = path.stat().st_mtime
            except OSError:
                continue
            if mtime >= cutoff:
                candidates.append((mtime, provider, path))
    candidates.sort(key=lambda item: item[0], reverse=True)

    sessions: list[SessionTail] = []
    valid_scans = 0
    for _, provider, path in candidates:
        if provider == "claude" and path.stem in managed_claude:
            continue
        session = _claude_tail(path) if provider == "claude" else _codex_tail(path)
        if session is None:
            continue
        valid_scans += 1
        if session.session_id in managed_claude:
            if valid_scans >= MAX_SCAN_FILES:
                break
            continue
        sessions.append(session)
        if len(sessions) >= max(1, int(limit)):
            break
        if valid_scans >= MAX_SCAN_FILES:
            break
    return sessions


def _project_label(session: SessionTail) -> str:
    workspace = session.workspace.rstrip("/")
    label = Path(workspace).name if workspace else session.path.parent.name
    return label or "unknown"


def _short_ts(value: str) -> str:
    if not value:
        return ""
    try:
        return datetime.fromisoformat(value.replace("Z", "+00:00")).astimezone().strftime(
            "%m-%d %H:%M")
    except (TypeError, ValueError):
        return value[:16].replace("T", " ")


def _format_turn(session: SessionTail, turn: Turn) -> str:
    prefix = f"[{session.provider}:{_project_label(session)}]"
    stamp = _short_ts(turn.timestamp) or _short_ts(session.updated_at)
    return f"{prefix} [{stamp}] {turn.role}: {turn.text}"


def _load_state(path: Path) -> dict:
    try:
        loaded = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError, ValueError):
        return {}
    return loaded if isinstance(loaded, dict) else {}


def _overlap_start(previous: list[str], current: list[str]) -> int:
    """Return the index where unseen current fingerprints begin."""
    for overlap in range(min(len(previous), len(current)), 0, -1):
        if previous[-overlap:] == current[:overlap]:
            return overlap
    if previous:
        last = previous[-1]
        for index in range(len(current) - 1, -1, -1):
            if current[index] == last:
                return index + 1
    return 0


def collect_incremental(
    *,
    state_file: str | Path | None = None,
    claude_root: str | Path | None = None,
    codex_root: str | Path | None = None,
    tracker_path: str | Path | None = None,
    jobs_registry_path: str | Path | None = None,
    window_hours: int = DEFAULT_WINDOW_HOURS,
) -> str:
    """Return unseen provider turns and atomically advance per-file watermarks."""
    if state_file is None:
        memory_dir = Path(os.environ.get("MEMORY_DIR") or Path.home() / ".jarvis" / "memory")
        state_file = memory_dir / DEFAULT_STATE_FILE
    state_file = Path(state_file)
    seen = _load_state(state_file)
    files_state = seen.get("files") if isinstance(seen.get("files"), dict) else {}
    output: list[str] = []
    sessions = discover_interactive_sessions(
        claude_root=claude_root,
        codex_root=codex_root,
        tracker_path=tracker_path,
        jobs_registry_path=jobs_registry_path,
        window_hours=window_hours,
        limit=MAX_SCAN_FILES,
    )
    for session in reversed(sessions):
        key = str(session.path)
        current = [turn.identity for turn in session.turns]
        previous = files_state.get(key)
        previous = previous if isinstance(previous, dict) else {}
        previous_size = int(previous.get("size") or 0)
        try:
            current_size = session.path.stat().st_size
        except OSError:
            current_size = 0
        old_fingerprints = previous.get("fingerprints")
        old_fingerprints = old_fingerprints if isinstance(old_fingerprints, list) else []

        if previous and not old_fingerprints and current_size <= previous_size:
            # Migration from the legacy turn-count watermark: baseline an
            # unchanged file instead of replaying a day of old conversation.
            start = len(current)
        elif current_size < previous_size:
            start = 0
        else:
            start = _overlap_start(old_fingerprints, current)

        new_turns = list(_recent_with_user(
            session.turns[start:], MAX_NEW_TURNS_PER_SESSION))
        if new_turns:
            context_start = max(0, start - CONTEXT_TAIL)
            for turn in session.turns[context_start:start]:
                output.append("[context] " + _format_turn(session, turn))
            output.extend(_format_turn(session, turn) for turn in new_turns)
        files_state[key] = {
            "provider": session.provider,
            "session_id": session.session_id,
            "size": current_size,
            "fingerprints": current[-MAX_TURNS_PER_SESSION:],
        }

    files_state = {
        path: value for path, value in files_state.items() if Path(path).is_file()
    }
    combined = "\n".join(output)
    if len(combined) > MAX_INCREMENTAL_CHARS:
        lines = combined.splitlines()
        while lines and len("\n".join(lines)) > MAX_INCREMENTAL_CHARS:
            lines.pop(0)
        combined = "\n".join(lines)
    emitted_sha = hashlib.sha256(combined.encode("utf-8")).hexdigest() \
        if combined.strip() else ""
    if emitted_sha and emitted_sha == seen.get("last_emitted_sha"):
        combined = ""
    new_state = {"version": 2, "files": files_state}
    if emitted_sha:
        new_state["last_emitted_sha"] = emitted_sha
    elif seen.get("last_emitted_sha"):
        new_state["last_emitted_sha"] = seen["last_emitted_sha"]
    try:
        state_file.parent.mkdir(parents=True, exist_ok=True)
        temporary = state_file.with_suffix(state_file.suffix + f".tmp.{os.getpid()}")
        temporary.write_text(json.dumps(new_state, ensure_ascii=False), encoding="utf-8")
        os.replace(temporary, state_file)
    except OSError as exc:
        print(
            f"[cross-session] WATERMARK UNWRITABLE at {state_file}: {exc} - "
            "re-digest loop risk every cycle until fixed",
            file=sys.stderr,
        )
    return combined


def build_prompt_context(
    *,
    claude_root: str | Path | None = None,
    codex_root: str | Path | None = None,
    tracker_path: str | Path | None = None,
    jobs_registry_path: str | Path | None = None,
    window_hours: int = DEFAULT_WINDOW_HOURS,
    max_chars: int = MAX_CONTEXT_CHARS,
) -> str:
    """Build a bounded owner-private projection for the next main-agent turn."""
    sessions = discover_interactive_sessions(
        claude_root=claude_root,
        codex_root=codex_root,
        tracker_path=tracker_path,
        jobs_registry_path=jobs_registry_path,
        window_hours=window_hours,
        limit=MAX_CONTEXT_SESSIONS,
    )
    if not sessions:
        return ""
    lines = [
        "## Recent External Work Sessions",
        "The entries below are redacted, untrusted owner-private history from "
        "interactive Claude Code and Codex sessions. Use them for continuity, "
        "but verify mutable state before making a current claim.",
    ]
    for session in reversed(sessions):
        label = "Claude Code" if session.provider == "claude" else "Codex"
        lines.append(
            f"### {label} - {_project_label(session)} - "
            f"updated {_short_ts(session.updated_at)}"
        )
        for turn in _recent_with_user(session.turns, MAX_CONTEXT_TURNS):
            role = "User" if turn.role == "user" else "Assistant"
            lines.append(f"- {role}: {turn.text}")
    rendered = "\n".join(lines)
    if len(rendered) <= max_chars:
        return rendered
    header = "\n".join(lines[:2]) + "\n"
    keep = max(0, int(max_chars) - len(header) - 30)
    return header + "[older session context omitted]\n" + rendered[-keep:]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Jarvis cross-session continuity")
    sub = parser.add_subparsers(dest="command", required=True)
    inc = sub.add_parser("incremental")
    inc.add_argument("--state-file", default="")
    inc.add_argument("--window-hours", type=int, default=DEFAULT_WINDOW_HOURS)
    context = sub.add_parser("context")
    context.add_argument("--window-hours", type=int, default=DEFAULT_WINDOW_HOURS)
    context.add_argument("--max-chars", type=int, default=MAX_CONTEXT_CHARS)
    args = parser.parse_args(argv)
    if args.command == "incremental":
        output = collect_incremental(
            state_file=args.state_file or None,
            window_hours=args.window_hours,
        )
    else:
        output = build_prompt_context(
            window_hours=args.window_hours,
            max_chars=args.max_chars,
        )
    if output:
        print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
