"""Bounded discovery of Claude Code and Codex work sessions.

Only metadata and a short first-user-message label are read. Full transcripts,
reasoning, and tool payloads stay in their provider-native stores.
"""

from __future__ import annotations

import json
import re
import time
from datetime import datetime
from pathlib import Path

from core.textutil import extract_text

DEFAULT_DAYS = 30
DEFAULT_LIMIT = 30
MAX_SCAN_FILES = 300
TITLE_CHARS = 96
BACKWARD_CHUNK_BYTES = 256 * 1024
MAX_RECENT_SCAN_BYTES = 16 * 1024 * 1024
SYNTHETIC_USER_PREFIXES = (
    "This session is being continued from a previous conversation",
    "Caveat: The messages below were generated by the user while running local commands",
    "Set model to ",
    "你是一个对话压缩器",
    "The following is the Codex agent history whose request action",
)


def _iso_mtime(path: Path) -> str:
    try:
        return datetime.fromtimestamp(path.stat().st_mtime).astimezone().isoformat(
            timespec="seconds")
    except OSError:
        return ""


def _title(text: str, fallback: str) -> str:
    text = re.sub(r"<[^>]+>", " ", str(text or ""))
    text = re.sub(r"\s+", " ", text).strip()
    for prefix in ("[SESSION COMPACT]", "[User message]", "[user]"):
        if text.startswith(prefix):
            text = text[len(prefix):].strip()
    if not text:
        return fallback
    return text if len(text) <= TITLE_CHARS else text[:TITLE_CHARS].rstrip() + "…"


def _recent(paths, days: int, limit: int) -> list[Path]:
    cutoff = time.time() - max(1, int(days)) * 86400
    candidates = []
    for path in paths:
        try:
            mtime = path.stat().st_mtime
        except OSError:
            continue
        if mtime >= cutoff:
            candidates.append((mtime, path))
    candidates.sort(key=lambda item: item[0], reverse=True)
    return [path for _, path in candidates[:min(MAX_SCAN_FILES, max(limit * 4, limit))]]


def _claude_paths(root: Path):
    if not root.is_dir():
        return []
    paths = []
    for project in root.iterdir():
        if project.is_dir():
            paths.extend(project.glob("*.jsonl"))
    return paths


def _latest_user_text(path: Path, extractor,
                      max_bytes: int = MAX_RECENT_SCAN_BYTES) -> str:
    """Find the newest real user record by scanning JSONL backwards in chunks."""
    try:
        with path.open("rb") as fh:
            size = fh.seek(0, 2)
            cutoff = max(0, size - max_bytes)
            position = size
            remainder = b""
            while position > cutoff:
                chunk_size = min(BACKWARD_CHUNK_BYTES, position - cutoff)
                position -= chunk_size
                fh.seek(position)
                parts = (fh.read(chunk_size) + remainder).split(b"\n")
                remainder = parts[0]
                for raw in reversed(parts[1:]):
                    if not raw:
                        continue
                    try:
                        item = json.loads(raw.decode("utf-8", errors="ignore"))
                    except (json.JSONDecodeError, UnicodeDecodeError, ValueError):
                        continue
                    if isinstance(item, dict) and (text := extractor(item)):
                        return text
            if cutoff == 0 and remainder:
                try:
                    item = json.loads(remainder.decode("utf-8", errors="ignore"))
                except (json.JSONDecodeError, UnicodeDecodeError, ValueError):
                    return ""
                if isinstance(item, dict):
                    return extractor(item)
    except OSError:
        return ""
    return ""


def _claude_user_text(item: dict) -> str:
    if item.get("type") != "user" or item.get("isSidechain"):
        return ""
    candidate = extract_text((item.get("message") or {}).get("content"))
    if candidate.startswith(("<system-reminder>", "<local-command-caveat>",
                             "[Tool result]", *SYNTHETIC_USER_PREFIXES)):
        return ""
    return candidate


def _codex_user_text(item: dict) -> str:
    payload = item.get("payload") or {}
    if item.get("type") != "event_msg" or payload.get("type") != "user_message":
        return ""
    candidate = str(payload.get("message") or "").strip()
    if candidate.startswith(SYNTHETIC_USER_PREFIXES):
        return ""
    return candidate


def _parse_claude(path: Path) -> dict | None:
    session_id = path.stem
    workspace = ""
    started_at = ""
    first_user = ""
    model = ""
    try:
        with path.open(encoding="utf-8", errors="ignore") as fh:
            for index, line in enumerate(fh):
                if index >= 240:
                    break
                try:
                    item = json.loads(line)
                except (json.JSONDecodeError, ValueError):
                    continue
                if item.get("sessionId"):
                    session_id = str(item["sessionId"])
                if not workspace and item.get("cwd"):
                    workspace = str(item["cwd"])
                if not started_at and item.get("timestamp"):
                    started_at = str(item["timestamp"])
                candidate = _claude_user_text(item)
                if candidate and not first_user:
                    first_user = candidate
                if item.get("type") == "assistant" and not model:
                    model = str((item.get("message") or {}).get("model", ""))
    except OSError:
        return None
    first_user = _latest_user_text(path, _claude_user_text) or first_user
    fallback = f"Claude session {session_id[:8]}"
    return {
        "provider": "claude",
        "session_id": session_id,
        "workspace": workspace or path.parent.name,
        "title": _title(first_user, fallback),
        "started_at": started_at,
        "updated_at": _iso_mtime(path),
        "model": model,
        "path": str(path),
    }


def _codex_paths(root: Path):
    return root.rglob("*.jsonl") if root.is_dir() else []


def _parse_codex(path: Path) -> dict | None:
    session_id = path.stem.rsplit("-", 5)[-1]
    workspace = ""
    started_at = ""
    first_user = ""
    model = ""
    is_subagent = False
    try:
        with path.open(encoding="utf-8", errors="ignore") as fh:
            for index, line in enumerate(fh):
                if index >= 240:
                    break
                try:
                    item = json.loads(line)
                except (json.JSONDecodeError, ValueError):
                    continue
                payload = item.get("payload") or {}
                if item.get("type") == "session_meta":
                    session_id = str(payload.get("id") or payload.get("session_id")
                                     or session_id)
                    workspace = str(payload.get("cwd") or workspace)
                    started_at = str(payload.get("timestamp") or item.get("timestamp")
                                     or started_at)
                    model = str(payload.get("model_provider") or model)
                    source = payload.get("source")
                    is_subagent = (payload.get("thread_source") == "subagent"
                                   or (isinstance(source, dict) and "subagent" in source))
                elif item.get("type") == "turn_context":
                    workspace = str(payload.get("cwd") or workspace)
                    model = str(payload.get("model") or model)
                else:
                    candidate = _codex_user_text(item)
                    if candidate and not first_user:
                        first_user = candidate
    except OSError:
        return None
    if is_subagent:
        return None
    first_user = _latest_user_text(path, _codex_user_text) or first_user
    fallback = f"Codex session {session_id[:8]}"
    return {
        "provider": "codex",
        "session_id": session_id,
        "workspace": workspace or path.parent.name,
        "title": _title(first_user, fallback),
        "started_at": started_at,
        "updated_at": _iso_mtime(path),
        "model": model,
        "path": str(path),
    }


def _matter_links() -> dict[tuple[str, str], str]:
    try:
        from dashboard.db import get_db
        rows = get_db().execute(
            "SELECT provider, entity_id, matter_id FROM matter_links "
            "WHERE entity_type = 'session'"
        ).fetchall()
        return {(str(r[0]), str(r[1])): str(r[2]) for r in rows}
    except Exception:
        return {}


def discover_sessions(provider: str = "", days: int = DEFAULT_DAYS,
                      limit: int = DEFAULT_LIMIT,
                      claude_root: str | Path | None = None,
                      codex_root: str | Path | None = None,
                      include_matter_links: bool = True) -> list[dict]:
    """Return recent provider sessions, newest first.

    Roots are injectable for tests. Discovery only scans top-level Claude
    project transcripts (never subagents/tool-results) and Codex rollout JSONL.
    """
    provider = str(provider or "").strip().lower()
    if provider not in {"", "claude", "codex"}:
        raise ValueError(f"unsupported session provider: {provider}")
    limit = max(1, min(int(limit), 100))
    home = Path.home()
    claude_root = Path(claude_root) if claude_root else home / ".claude" / "projects"
    codex_root = Path(codex_root) if codex_root else home / ".codex" / "sessions"
    sessions: list[dict] = []
    if provider in {"", "claude"}:
        for path in _recent(_claude_paths(claude_root), days, limit):
            item = _parse_claude(path)
            if item:
                sessions.append(item)
    if provider in {"", "codex"}:
        for path in _recent(_codex_paths(codex_root), days, limit):
            item = _parse_codex(path)
            if item:
                sessions.append(item)
    sessions.sort(key=lambda item: item.get("updated_at", ""), reverse=True)
    if include_matter_links:
        linked = _matter_links()
        for item in sessions:
            item["matter_id"] = linked.get(
                (item["provider"], item["session_id"]), "")
    return sessions[:limit]
